# Generated by Django 5.1 on 2024-08-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='titel',
        ),
    ]
