# Generated by Django 5.1 on 2024-08-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_book_titel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='info',
        ),
        migrations.RemoveField(
            model_name='author',
            name='year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='info',
        ),
    ]
